name: .NetCore app to an azure wap

env:
  AZURE_WEBAPP_NAME: myfirstweb-app1-dotnet
  AZURE_WEBAPP_PACKAGE_PATH: '.'             
  #ROOT_PATH: './actions/aspnet6'     
  DOTNET_VERSION: '6.0.x'                    

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build with dotnet
        run: dotnet build --configuration Release
        #working-directory: ${{env.ROOT_PATH}}

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        #working-directory: ${{env.ROOT_PATH}}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp 
          
      - name: 'Az CLI login with subscription'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
        
        

  deploy_dev:
    name: dev
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: "https://myfirstweb-app1-dotnet.azurewebsites.net"

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.sec }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
